# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-29 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mce_filebrowser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebrowserfile',
            name='file_name',
            field=models.CharField(default='untitled', max_length=255),
            preserve_default=False,
        ),
    ]
